services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://ferretdb:27017/animebeat
    depends_on:
      ferretdb:
        condition: service_started

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://richar01:cRVlSAnm5kXKV0vnPgtbymvTCYMqI8jm75Kg97Z1ND1nFbmxg4zNLiSYmRd5K3q5@o7nynhty6rb51tlyz278mhg3:5432/postgres
